version: '3.8'
services:
  todolist-app:
    build: .
    ports:
      - "8080:8080"
  h2-db:
    image: oscarfonts/h2-docker
    ports:
      - "9092:9092"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers -advertiseAddr h2-db"
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data:
